# version: '3.9'
# services:
#   db:
#     image: postgres:latest
#     restart: always
#     ports:
#       - '5432:5432'
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     volumes:
#       - db:/var/lib/postgresql/data
#   backend:
#     build: ../Backend/src/
#     ports:
#       - '9991:80'
#     container_name: backend
#     environment:
#       DB_HOST: 'db'
#       DB_PORT: '5432'
#       DB_USER: 'postgres'
#       DB_PASSWORD: 'postgres'
#       DB_NAME: 'postgres'
#       SECRET_KEY: 'sdkfskjfaskahskjfhahfkashfda'
#       ALGORITHM: 'HS256'
#     networks:
#       my-network:
#         aliases:
#           - server
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ../frontend/refferly
#     ports:
#       - '3000:3000'
#     container_name: frontend
#     stdin_open: true
#     depends_on:
#       - backend
#     networks:
#       my-network:
#         aliases:
#           - frontend
#     command: npm start

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     volumes:
#         - ../:/var/www
#         - ../nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
#     ports:
#         - 80:80
#     networks:
#         - my-network
#     depends_on:
#         - server
#         - client
#   # nginx:
#   #   build:
#   #     context: ../nginx
#   #   container_name: nginx
#   #   ports:
#   #     - '9998:80'
#   #   depends_on:
#   #     - backend
#   #     - frontend

# volumes:
#   db:
#     driver: local

# networks:
#     my-network:
